import type { SelectOption } from '../form/form.types';

const BIH_MUNICIPALITIES = [
  // Federation of Bosnia and Herzegovina (79)
  'Banovići',
  'Bihać',
  'Bosanska Krupa',
  'Bosanski Petrovac',
  'Bosansko Grahovo',
  'Breza',
  'Bugojno',
  'Busovača',
  'Bužim',
  'Čapljina',
  'Cazin',
  'Čelić',
  'Centar',
  'Čitluk',
  'Doboj Istok',
  'Doboj Jug',
  'Dobretići',
  'Domaljevac-Šamac',
  'Donji Vakuf',
  'Drvar',
  'Foča-Ustikolina',
  'Fojnica',
  'Glamoč',
  'Goražde',
  'Gornji Vakuf-Uskoplje',
  'Gračanica',
  'Gradačac',
  'Grude',
  'Hadžići',
  'Ilidža',
  'Ilijaš',
  'Jablanica',
  'Jajce',
  'Kakanj',
  'Kalesija',
  'Kiseljak',
  'Kladanj',
  'Ključ',
  'Konjic',
  'Kreševo',
  'Kupres',
  'Livno',
  'Ljubuški',
  'Lukavac',
  'Maglaj',
  'Mostar',
  'Neum',
  'Novi Grad',
  'Novi Travnik',
  'Novo Sarajevo',
  'Odžak',
  'Olovo',
  'Orašje',
  'Pale-Prača',
  'Posušje',
  'Prozor-Rama',
  'Ravno',
  'Sanski Most',
  'Sapna',
  'Srebrenik',
  'Stari Grad',
  'Stolac',
  'Široki Brijeg',
  'Teočak',
  'Tešanj',
  'Tomislavgrad',
  'Travnik',
  'Trnovo (FBiH)',
  'Tuzla',
  'Usora',
  'Vareš',
  'Velika Kladuša',
  'Visoko',
  'Vitez',
  'Vogošća',
  'Zavidovići',
  'Zenica',
  'Žepče',
  'Živinice',
  // Republika Srpska (64)
  'Banja Luka',
  'Berkovići',
  'Bijeljina',
  'Bileća',
  'Bosanska Kostajnica',
  'Bosanski Brod',
  'Bratunac',
  'Čajniče',
  'Čelinac',
  'Derventa',
  'Doboj',
  'Donji Žabar',
  'Foča',
  'Gacko',
  'Gradiška',
  'Han Pijesak',
  'Istočna Ilidža',
  'Istočno Sarajevo',
  'Istočni Drvar',
  'Istočni Mostar',
  'Istočni Stari Grad',
  'Istočno Novo Sarajevo',
  'Jezero',
  'Kalinovik',
  'Kneževo',
  'Kozarska Dubica',
  'Kotor Varoš',
  'Krupa na Uni',
  'Kupres (RS)',
  'Laktaši',
  'Ljubinje',
  'Lopare',
  'Milići',
  'Modriča',
  'Mrkonjić Grad',
  'Nevesinje',
  'Novi Grad (RS)',
  'Novo Goražde',
  'Osmaci',
  'Oštra Luka',
  'Pale',
  'Pelagićevo',
  'Petrovac',
  'Petrovo',
  'Prijedor',
  'Prnjavor',
  'Ribnik',
  'Rogatica',
  'Rudo',
  'Šamac',
  'Šekovići',
  'Šipovo',
  'Sokolac',
  'Srbac',
  'Srebrenica',
  'Stanari',
  'Teslić',
  'Trebinje',
  'Trnovo (RS)',
  'Ugljevik',
  'Višegrad',
  'Vlasenica',
  'Vukosavlje',
  'Zvornik',
  // Brčko District
  'Brčko',
] as const;

export const BIH_CITIES = [...BIH_MUNICIPALITIES].sort((a, b) =>
  a.localeCompare(b, 'bs'),
) as readonly string[];

export const BIH_CITY_OPTIONS: SelectOption[] = BIH_CITIES.map((city) => ({
  value: city,
  label: city,
}));
